extends JsonSerializable
class_name LoginWithCustomIdRequest

# Unique identifier for the title, found in the Settings > Game Properties section of the PlayFab developer site when a title has been selected.
var TitleId: String

# Automatically create a PlayFab account if one is not currently linked to this ID.
var CreateAccount: bool

# Custom unique identifier for the user, generated by the title.
var CustomId: String

# The optional custom tags associated with the request (e.g. build number, external trace identifiers, etc.).
var CustomTags: Dictionary

# Base64 encoded body that is encrypted with the Title's public RSA key (Enterprise Only).
var EncryptedRequest: String

# Flags for which pieces of info to return for the user.
var InfoRequestParameters: GetPlayerCombinedInfoRequestParams

# Player secret that is used to verify API request signatures (Enterprise Only).
var PlayerSecret: String


func _get_type_for_property(property_name: String) -> String:
	match property_name:
		"InfoRequestParameters":
			return "GetPlayerCombinedInfoRequestParams"
		_:
			pass
	
	push_error("Could not find mapping for property: " + property_name)
	return super._get_type_for_property(property_name)
	
