name: CI Godot 4

# Controls when the workflow will run
on:
  push:
    branches:
      - develop
      - main
      - godot4
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - develop
      - main
      - godot4

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ADDON_NAME: godot-playfab
  GODOT_PLAYFAB_TEST_USER: ${{ secrets.GODOT_PLAYFAB_TEST_USER }}
  GODOT_PLAYFAB_TEST_PASSWORD: ${{ secrets.GODOT_PLAYFAB_TEST_PASSWORD }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: "🤖 unit tests on Godot v${{ matrix.godot-version }}-${{ matrix.godot-status-version }} (${{ matrix.name }})"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        os: [ubuntu-22.04]
        godot-version: ['4.2', '4.2.1', '4.2.2', '4.3']
        godot-status: ['stable']

    steps:
      - name: "📦 Checkout"
        uses: actions/checkout@v4

      - name: "🧪 Run Unit Tests on Godot version ${{ matrix.godot-version }}"
        uses: MikeSchulze/gdUnit4-action@v1
        with:
          godot-version: ${{ matrix.godot-version }}
          godot-status: ${{ matrix.godot-status }}
          version: "latest"
          paths: |
            'res://addons/godot-playfab/test'
          timeout: 10
          report-name: report_gdUnit4_Godot${{ matrix.godot-version }}-${{ matrix.godot-status }}.xml

